### ISSUE TITLE
Trying to parse attachments when unavailable leading to NullPointerException

### ISSUE THREAD

**Issue by aarahman7** [shivam1608/JMailTM#5]
<img width="885" alt="image" src="https://github.com/shivam1608/JMailTM/assets/6194278/f895f7f3-758b-4400-8f1e-c4a170db124d">

When there are no attachments, we are still trying to parse the attachment which leads to NullPointerException. Shall we have an if condition so that the attachments will be parsed only if `hasAttachments` is true.

**Comment by aarahman7** [comment]
Can I take this up and fix this issue?

**Comment by shivam1608** [comment]
well hey👋@aarahmanqa , thanks for pointing out this issue.
maybe mail.tm has gone through some changes in their api because i remember it used to return an empty `array[]` keeping that aside i would love to merge your pull request so you can work on that bug. (I'm just hoping it doesn't break anything 😜)

**Comment by aarahman7** [comment]
Thanks Shivam. I would like to ask one more thing. There are many places here that are prone to NullPointerException.

Like, json.get("html").toString();

In case, the json.get("html") returns null, we would get NullPointerException. Rather it would be good if we can get it as null itself.

To overcome such issues, I used to follow [this](https://towardsdev.com/stop-checking-for-nulls-in-java-593a1f1a0c2f). Shall I implement the same here as well?

**Comment by shivam1608** [comment]
the mail.tm api promise the value of the key `html` in the json so it would never throw `NullPointer` because mailtm converts raw text to html format and even if you supply no body to the smtp protocol its going to return an empty `array[]`
so i don't think there is any need for it.

**Comment by aarahman7** [comment]
Yeah I agree to your point Shivam. I have mentioned "html" just for reference. It could happen in any field. When a field is null, we need to accept it as null, right? It would be better instead of throwing NullPointerException. I will propose my solution as enhancement and raise PR, we shall discuss it. Please feel free to close it if not needed.

**Comment by aarahman7** [comment]
I have raised PR for this issue. Request you to kindly go through the same.
https://github.com/shivam1608/JMailTM/pull/6

**Comment by shivam1608** [comment]
Fixed in pull request #6 👍

**Comment by aarahman7** [comment]
@shivam1608 , when shall we expect the fix in remote build?
