### ISSUE TITLE
Add null checks on all the field retrievals to avoid NullPointerException

### ISSUE THREAD

**Issue by aarahman7** [shivam1608/JMailTM#8]
Whenever we retrieve a value from the json field, we use .toString() which could throw NullPointerException. That field may be allowed to have null but since we have .toString() we would end up with NPE. This PR aims at avoiding such NPE. Its a better alternative to null check.
PFB the PR raised for the same.
#7

**Comment by shivam1608** [comment]
Done in #7
Thanks for the contribution @aarahmanqa
